version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18     
    commands:
      - npm  install -g serverless
      - npm install
  build:
    commands:
      - serverless deploy --stage ${STAGE_NAME}
artifacts:
  files:
    - '**/*'
cache:
  paths:
    - node_modules