version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18     
  pre_build:
    commands:
      - echo "Entered pre-build phase"
      - npm install
artifacts:
  files:
    - '**/*'
cache:
  paths:
    - node_modules